### ISSUE TITLE
Add test case generation

### ISSUE THREAD

**Issue by codykenb** [gintool/gin#15]
Use Evosuite before applying GIN 
(do we want to integrate evolsuite with gin?)

Using more tests in GIN should give a smoother gradient on a problem, provided each test is somewhat independent. Not sure what fitness evosuite uses, but it could certainly help to automatically boost the test cases in GIN.

**Comment by drdrwhite** [comment]
Evosuite website:

http://www.evosuite.org

Source:

https://github.com/EvoSuite/evosuite

It would make sense to contact Andrea or Gordon (EvoSuite maintainers) to ask them how best to approach this integration. I believe EvoSuite generates jUnit tests, so it could be a great fit.

**Comment by drdrwhite** [comment]
We've made progress on this; TBA.

**Comment by justynapt** [comment]
Added support for EvoSuite for Maven projects a while back, including automatic update of the pom file. gin.util.TestCaseGenerator also generates tests for Gradle projects though currently EvoSuite dependency needs to be added manually to the project if not present. Since basic test case generation is implemented (though needs testing), I'm closing this issue.
