### ISSUE TITLE
Upgrade JavaParser dependency

### ISSUE THREAD

**Issue by matozoid** [gintool/gin#32]
It's rather behind, and much has been improved.

**Comment by justynapt** [comment]
Test failures when trying to upgrade beyond 3.65. Compiles fine with 3.12 if the following changes are made: Module{Opens/Uses/Provides/Requires/Exports/}Stmt -> Module{Opens/Uses/Provides/Requires/Exports/}Directive
ForeachStmt -> ForEachStmt
SwitchEntryStmt -> SwitchEntry
for BreakStmt: removeLabel -> removeValue
in any case test failures need to be resolved first

**Comment by sandybrownlee** [comment]
Now updated to JavaParser 3.22.1. Required further changes:

- modifiers like "public" are now added to the node list in SourceFileStatement. This means that there are some extra node IDs (which are also statement IDs) - so the tests that fail are those expecting to see particular node IDs for the example source files. It might break things if anyone runs something that expects to see a particular node ID for a target source file (e.g., trying to run PatchAnalyser on patches generated by an old version of Gin on the updated one). Random number generator will also produce a different stream of patches as the total number of statements to choose from is different. Amended README to reflect this and updated unit tests to reflect new expected IDs.
- "insert" edits needed some tweaking because of changed treatment of break/continue statements (which was then reverted in a still later version of JP)
- extra node types added to CloneVisitorCopyIDs
- changed name of some JavaParser classes

**Comment by sandybrownlee** [comment]
[4122ea4](https://github.com/gintool/gin/commit/4122ea48b8d9cac07e00a74cb13293a6addeefd8) now updated to 3.24.0. Closing.
